<template>
    <main>
        <HeroIntro></HeroIntro>
        <ContactSection></ContactSection>
        <PaletteSelect></PaletteSelect>
        <WorksSection></WorksSection>
        <ContactSection></ContactSection>
    </main>
</template>