<template>
    <main>
        <HeroIntro></HeroIntro>
        <PaletteSelect></PaletteSelect>
        <AboutSection></AboutSection>
        <SkillsList></SkillsList>
        <WorksSection></WorksSection>
        <ContactSection></ContactSection>
    </main>
</template>